spring:
  profiles:
    active: local
  application:
    name: casy-ai-agent
  # 数据库配置
  datasource:
    # mysql配置
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/casy-ai?allowMultiQueries=true
#    username: root
#    password: root
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://pgm-2zej9ksewfj9yw903o.rwlb.rds.aliyuncs.com:5432/casy_aip_agent
     username: my_user
     password: Hxb@93393
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/sql/schema-postgresql.sql # 无效？？

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.casy.casyaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE